services:
  # 메인 사용자용 프론트
  fitneeds-enduser-frontend:
    build:
      context: ./enduser-frontend
    container_name: fitneeds-enduser-frontend
    ports:
      - "8020:80"
    depends_on:
      - fitneeds-enduser-backend
    networks:
      - fitneeds-net
    restart: unless-stopped

  # 메인 사용자용 백엔드
  fitneeds-enduser-backend:
    build:
      context: ./enduser-backend
    container_name: fitneeds-enduser-backend
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://fitneeds-db:3306/fitneedsdb
      - SPRING_DATASOURCE_USERNAME=fitneeds
      - SPRING_DATASOURCE_PASSWORD=fullstack2025
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - fitneeds-net
    depends_on:
      - fitneeds-db
    restart: unless-stopped

  # 관리자용 프론트
  fitneeds-admin-frontend:
    build:
      context: ./admin-frontend
    container_name: fitneeds-admin-frontend
    ports:
      - "8021:80"
    depends_on:
      - fitneeds-admin-backend
    networks:
      - fitneeds-net
    restart: unless-stopped

  # 관리자용 백엔드
  fitneeds-admin-backend:
    build:
      context: ./admin-backend
    container_name: fitneeds-admin-backend
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://fitneeds-db:3306/fitneedsdb
      - SPRING_DATASOURCE_USERNAME=fitneeds
      - SPRING_DATASOURCE_PASSWORD=fullstack2025
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - fitneeds-net
    depends_on:
      - fitneeds-db
    restart: unless-stopped

  # 공용 MariaDB
  fitneeds-db:
    image: mariadb:11
    ports:
      - "3307:3306"
    container_name: fitneeds-db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=rfullstack2025
      - MARIADB_DATABASE=fitneedsdb
      - MARIADB_USER=fitneeds
      - MARIADB_PASSWORD=fullstack2025
    volumes:
      - fitneeds-db-data:/var/lib/mysql
      - ./enduser-backend/src/main/resources/sql/create_table.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf:ro
    networks:
      - fitneeds-net

networks:
  fitneeds-net:
    driver: bridge

volumes:
  fitneeds-db-data:
