version: "3.9"

services:
  # 메인 사용자용 프론트
  fitneeds-frontend:
    build:
      context: ./frontend-enduser
    container_name: fitneeds-enduser-frontend
    ports:
      - "8020:80"
    depends_on:
      - backend-enduser
    networks:
      - fitneeds-net
    restart: unless-stopped

  # 메인 사용자용 백엔드
  backend-enduser:
    build:
      context: ./backend-enduser
    container_name: fitneeds-enduser-backend
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://fitneeds-db:3306/fitneedsdb
      - SPRING_DATASOURCE_USERNAME=fituser
      - SPRING_DATASOURCE_PASSWORD=fullstack2025
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - fitneeds-net
    depends_on:
      - fitneeds-db
    restart: unless-stopped

  # 관리자용 프론트
  fitneeds-admin-frontend:
    build:
      context: ./frontend-admin
    container_name: fitneeds-admin-frontend
    ports:
      - "8021:80"
    depends_on:
      - backend-admin
    networks:
      - fitneeds-net
    restart: unless-stopped

  # 관리자용 백엔드
  backend-admin:
    build:
      context: ./backend-admin
    container_name: fitneeds-admin-backend
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://fitneeds-db:3306/fitneedsdb
      - SPRING_DATASOURCE_USERNAME=fituser
      - SPRING_DATASOURCE_PASSWORD=fullstack2025
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - fitneeds-net
    depends_on:
      - fitneeds-db
    restart: unless-stopped

  # 공용 MariaDB
  fitneeds-db:
    image: mariadb:11
    container_name: fitneeds-db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=rfullstack2025
      - MARIADB_DATABASE=fitneedsdb
      - MARIADB_USER=fituser
      - MARIADB_PASSWORD=fullstack2025
    volumes:
      - fitneeds-db-data:/var/lib/mysql
    networks:
      - fitneeds-net

networks:
  fitneeds-net:
    driver: bridge

volumes:
  fitneeds-db-data:
